[build-system]
requires = [
  "setuptools >= 30.3.0",
  "wheel",
  "cffi",
  "setuptools_scm",
  "setuptools_scm_git_archive"
]

[tool.black]
line-length = 88
py36 = true
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | docs
  | misc
  | \.egg-info
)/
'''
